import { NextRequest, NextResponse } from "next/server";
import { createServiceSupabase } from "@/lib/supabase/service";
import { createApiSupabaseClient } from "@/lib/supabase/api";
import { getAal2UserOrThrow } from "@/lib/auth/api";
import { authErrorResponse } from "@/lib/auth/authError";
import { ensureInvoice } from "@/lib/payments/ensureInvoice";

// Invoice generation can invoke the PDF edge function + storage; give headroom.
export const maxDuration = 60;

/**
 * POST /api/payments/:id/invoice/regenerate — manual "Regenerate Invoice".
 *
 * Idempotent recovery for a payment whose invoice never generated (edge-fn/storage/DB
 * hiccup). Verifies the caller owns the payment and it is PAID, returns the EXISTING
 * invoice if one already exists (never duplicates), otherwise triggers the idempotent
 * worker. If the worker can't finish synchronously (in-progress / transient failure)
 * it responds 202 — the payment is now a recovery-sweeper candidate and will complete.
 */
export async function POST(
  req: NextRequest,
  context: { params: Promise<{ id: string }> },
) {
  try {
    const { id } = await context.params;

    // 1. Authenticate + ownership-scope (payments.patient_id == auth user id).
    const supabaseAuth = await createApiSupabaseClient(req);
    const user = await getAal2UserOrThrow(supabaseAuth);

    const service = createServiceSupabase();
    const { data: payment, error } = await service
      .from("payments")
      .select("id, status, invoice_url, invoice_number")
      .eq("id", id)
      .eq("patient_id", user.id)
      .maybeSingle();

    // Same 404 whether missing or not-owned — no existence leak.
    if (error || !payment) {
      return NextResponse.json({ error: "Payment not found" }, { status: 404 });
    }

    // 2. Already has an invoice → return it (idempotent, no duplicate).
    if (payment.invoice_url) {
      return NextResponse.json(
        { status: "exists", invoice_url: payment.invoice_url, invoice_number: payment.invoice_number },
        { status: 200 },
      );
    }

    // 3. Only paid payments can have an invoice.
    if (payment.status !== "paid") {
      return NextResponse.json({ error: "Payment is not completed" }, { status: 409 });
    }

    // 4. Trigger the idempotent worker.
    const result = await ensureInvoice(id, "manual");

    if (result.ok && result.url) {
      return NextResponse.json(
        { status: "generated", invoice_url: result.url, invoice_number: result.invoiceNumber },
        { status: 200 },
      );
    }

    // Being generated by another worker, or a transient failure that the recovery
    // sweeper will retry — tell the client to poll again shortly.
    return NextResponse.json(
      {
        status: result.outcome === "in_progress" ? "in_progress" : "queued",
        message: "Invoice is being generated. Please try again in a moment.",
      },
      { status: 202 },
    );
  } catch (err) {
    const authRes = authErrorResponse(err);
    if (authRes) return authRes;
    return NextResponse.json(
      { error: err instanceof Error ? err.message : "Server error" },
      { status: 500 },
    );
  }
}
