"use client";

import { useEffect, useMemo, useState } from "react";
import type { Json } from "@medilink/shared";
import { api } from "@medilink/shared";
import { createBrowserSupabaseClient } from "@/lib/supabase/client";
import { useI18n } from "@/i18n/I18nProvider";

function downloadRecord(rec: MedRecord, isAr: boolean) {
  const info = isAr ? rec.ar : rec.en;
  const lines = [
    "MEDILINK HEALTH RECORD",
    "═══════════════════════════════════════════════════",
    `Title    : ${info.title}`,
    `Doctor   : ${info.doctor}`,
    `Date     : ${rec.date}`,
    `Category : ${rec.category}`,
    "───────────────────────────────────────────────────",
    "Details:",
    info.detail,
    ...(info.tags && info.tags.length > 0 ? ["", `Tags: ${info.tags.join(" · ")}`] : []),
    "───────────────────────────────────────────────────",
    `Generated by MediLink on ${new Date().toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" })}`,
  ];
  const blob = new Blob([lines.join("\n")], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${info.title.replace(/\s+/g, "_")}_${rec.date.replace(/\s/g, "-")}.txt`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

const CATEGORIES = [
  { en: "All",            ar: "الكل" },
  { en: "Prescriptions",  ar: "الوصفات" },
  { en: "Lab Results",    ar: "نتائج التحاليل" },
  { en: "Imaging",        ar: "الأشعة" },
  { en: "Summaries",      ar: "ملخصات الزيارات" },
  { en: "Vaccinations",   ar: "اللقاحات" },
];

type MedRecord = {
  id: string;
  category: string;
  emoji: string;
  grad: string;
  date: string;
  en: { title: string; doctor: string; detail: string; tags?: string[] };
  ar: { title: string; doctor: string; detail: string; tags?: string[] };
};

/* ─── Aggregation: build the unified record feed from real sources ────── */
const GRADS = [
  "from-[#e8d5f0] to-[#d5e8f5]", "from-[#d5e8f5] to-[#ede0f8]", "from-[#ede0f8] to-[#d1fae5]",
  "from-[#d1fae5] to-[#e8d5f0]", "from-[#fde68a] to-[#d5e8f5]", "from-[#e8d5f0] to-[#fde68a]",
];
const CAT_EMOJI: Record<string, string> = {
  Prescriptions: "💊", "Lab Results": "🧪", Imaging: "🩻", Summaries: "📋", Vaccinations: "💉",
};
// document_type → page category
const DOC_CATEGORY: Record<string, string> = {
  prescription: "Prescriptions", imaging: "Imaging", report: "Summaries", insurance: "Summaries", other: "Summaries",
};

function fmtRecDate(iso: string | null) {
  if (!iso) return "";
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return "";
  return d.toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" });
}
function medNames(meds: Json[] | null): string[] {
  if (!Array.isArray(meds)) return [];
  return meds
    .map((m) => {
      if (typeof m === "string") return m;
      if (m && typeof m === "object" && !Array.isArray(m)) {
        const o = m as Record<string, Json>;
        const n = o.name ?? o.drug ?? o.medication;
        return typeof n === "string" ? n : "";
      }
      return "";
    })
    .filter(Boolean) as string[];
}

// Explicit row shapes — the nested selects degrade the generated types to an error union.
type RxRow = { id: string; medications: Json[] | null; instructions: string | null; issued_at: string; doctors?: { full_name?: string } | null };
type LabRowLite = { id: string; test_name: string | null; notes: string | null; uploaded_at: string };
type DocRow = { id: string; name: string; type: string; uploaded_at: string; appointment?: { doctor?: { full_name?: string } | null } | null };

function buildRecords(rx: RxRow[], labs: LabRowLite[], docs: DocRow[]): MedRecord[] {
  const rxRecs: (MedRecord & { _ts: number })[] = rx.map((p) => {
    const names = medNames(p.medications);
    const title = names.length ? names.join(", ") : "Prescription";
    const doctor = p.doctors?.full_name ?? "";
    const detail = p.instructions ?? "";
    const tags = names.slice(0, 3);
    const date = fmtRecDate(p.issued_at);
    return {
      id: `rx-${p.id}`, category: "Prescriptions", emoji: "💊", grad: "", date, _ts: Date.parse(p.issued_at) || 0,
      en: { title, doctor, detail, tags }, ar: { title, doctor, detail, tags },
    };
  });
  const labRecs: (MedRecord & { _ts: number })[] = labs.map((l) => {
    const title = l.test_name ?? "Lab Result";
    const detail = l.notes ?? "";
    const date = fmtRecDate(l.uploaded_at);
    return {
      id: `lab-${l.id}`, category: "Lab Results", emoji: "🧪", grad: "", date, _ts: Date.parse(l.uploaded_at) || 0,
      en: { title, doctor: "", detail }, ar: { title, doctor: "", detail },
    };
  });
  const docRecs: (MedRecord & { _ts: number })[] = docs.map((d) => {
    const category = DOC_CATEGORY[d.type] ?? "Summaries";
    const doctor = d.appointment?.doctor?.full_name ?? "";
    const date = fmtRecDate(d.uploaded_at);
    return {
      id: `doc-${d.id}`, category, emoji: CAT_EMOJI[category] ?? "📋", grad: "", date, _ts: Date.parse(d.uploaded_at) || 0,
      en: { title: d.name, doctor, detail: "" }, ar: { title: d.name, doctor, detail: "" },
    };
  });
  return [...rxRecs, ...labRecs, ...docRecs]
    .sort((a, b) => b._ts - a._ts)
    .map(({ _ts, ...rec }, i) => ({ ...rec, grad: GRADS[i % GRADS.length]! }));
}

export default function RecordsPage() {
  const { locale } = useI18n();
  const ar = locale === "ar";
  const supabase = useMemo(() => createBrowserSupabaseClient(), []);
  const [activeTab, setActiveTab]   = useState("All");
  const [search, setSearch]         = useState("");
  const [expanded, setExpanded]     = useState<string | null>(null);
  const [downloaded, setDownloaded] = useState<string | null>(null);
  const [records, setRecords]       = useState<MedRecord[]>([]);
  const [loading, setLoading]       = useState(true);
  const [error, setError]           = useState("");

  useEffect(() => {
    let active = true;
    setLoading(true);
    Promise.all([
      api.prescriptions.listPrescriptions(supabase).catch(() => []),
      api.labs.listLabResults(supabase).catch(() => []),
      api.records.listDocuments(supabase).catch(() => []),
    ])
      .then(([rx, labs, docs]) => {
        if (!active) return;
        setRecords(buildRecords(
          rx as unknown as RxRow[],
          labs as unknown as LabRowLite[],
          docs as unknown as DocRow[],
        ));
        setError("");
      })
      .catch(() => { if (active) setError(ar ? "تعذر تحميل السجلات." : "Could not load your records."); })
      .finally(() => { if (active) setLoading(false); });
    return () => { active = false; };
  }, [supabase, ar]);

  function handleDownload(rec: MedRecord) {
    downloadRecord(rec, ar);
    setDownloaded(rec.id);
    setTimeout(() => setDownloaded(null), 2000);
  }

  const filtered = records.filter(r => {
    const matchCat = activeTab === "All" || r.category === activeTab;
    const q = search.toLowerCase();
    return matchCat && (!q || r.en.title.toLowerCase().includes(q) || r.ar.title.includes(q) || r.en.doctor.toLowerCase().includes(q));
  });

  const EMOJI_FOR_CAT: Record<string, string> = {
    "Prescriptions": "💊", "Lab Results": "🧪", "Imaging": "🩻", "Summaries": "📋", "Vaccinations": "💉",
  };

  return (
    <div dir={ar ? "rtl" : "ltr"} className="min-h-screen bg-[#f9f4fa] dark:bg-[#0f0a1e] text-[#2E1A47] dark:text-[#DFC8E7]">

      {/* Hero */}
      <section className="py-10 px-6" style={{ background: "linear-gradient(140deg, #1e1038 0%, #2E1A47 55%, #1e1038 100%)" }}>
        <div className="max-w-3xl mx-auto">
          <p className="text-xs font-bold uppercase tracking-widest mb-2" style={{ color: "rgba(223,200,231,0.45)" }}>
            {ar ? "سجلاتي الصحية" : "My Health Records"}
          </p>
          <h1 className="font-black font-serif text-white mb-5" style={{ fontSize: "clamp(1.8rem, 3.5vw, 2.5rem)", lineHeight: 1.1 }}>
            {ar
              ? <><span className="block">سجلاتك الطبية</span><span className="block italic text-[#DFC8E7]">كلها هنا.</span></>
              : <><span className="block">Your medical records</span><span className="block italic text-[#DFC8E7]">all in one place.</span></>}
          </h1>
          {/* Search */}
          <div className="flex items-center gap-2 bg-white dark:bg-[#1a1030] rounded-2xl px-4 py-3 border border-white/10 shadow-lg max-w-lg">
            <svg className="w-4 h-4 text-[#2E1A47]/30 dark:text-[#DFC8E7]/30 flex-shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
            </svg>
            <input type="text" value={search} onChange={e => setSearch(e.target.value)}
              placeholder={ar ? "ابحث في سجلاتك..." : "Search your records..."}
              className="flex-1 text-sm outline-none text-[#2E1A47] dark:text-[#DFC8E7] placeholder-[#2E1A47]/30 dark:placeholder-[#DFC8E7]/30 bg-transparent" />
            {search && <button onClick={() => setSearch("")} className="text-[#2E1A47]/30 hover:text-[#2E1A47] dark:text-[#DFC8E7]/30 dark:hover:text-[#DFC8E7] transition-colors">
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></svg>
            </button>}
          </div>
        </div>
      </section>

      {/* Category tabs */}
      <section className="bg-white dark:bg-[#0d0820] border-b border-[#e7dcee] dark:border-[#2a1840] px-6 py-3 overflow-x-auto">
        <div className="max-w-3xl mx-auto flex gap-2 flex-nowrap">
          {CATEGORIES.map(c => (
            <button key={c.en} onClick={() => setActiveTab(c.en)}
              className={`px-4 py-1.5 rounded-full text-sm font-semibold whitespace-nowrap flex-shrink-0 border transition-all ${activeTab === c.en ? "bg-[#2E1A47] dark:bg-[#DFC8E7] text-white dark:text-[#1a1030] border-transparent" : "border-[#e7dcee] dark:border-[#3a2560] text-[#2E1A47]/60 dark:text-[#DFC8E7]/60 hover:border-[#2E1A47]/30"}`}>
              {EMOJI_FOR_CAT[c.en] ?? ""} {ar ? c.ar : c.en}
            </button>
          ))}
        </div>
      </section>

      {/* Records list */}
      <section className="py-8 px-6">
        <div className="max-w-3xl mx-auto">
          <p className="text-xs font-bold uppercase tracking-widest text-[#2E1A47]/35 dark:text-[#DFC8E7]/35 mb-5">
            {loading
              ? (ar ? "جارٍ التحميل…" : "Loading…")
              : ar ? `${filtered.length} سجل` : `${filtered.length} record${filtered.length !== 1 ? "s" : ""}`}
          </p>
          {loading ? (
            <div className="space-y-3">
              {[0, 1, 2, 3].map(i => (
                <div key={i} className="h-20 rounded-2xl border border-[#e7dcee] dark:border-[#3a2560] bg-white/50 dark:bg-[#1a1030]/50 animate-pulse" />
              ))}
            </div>
          ) : error ? (
            <div className="text-center py-20">
              <p className="text-4xl mb-4">⚠️</p>
              <p className="font-bold text-[#2E1A47] dark:text-[#DFC8E7] mb-2">{error}</p>
            </div>
          ) : filtered.length === 0 ? (
            <div className="text-center py-20">
              <p className="text-4xl mb-4">📂</p>
              <p className="font-bold text-[#2E1A47] dark:text-[#DFC8E7] mb-2">{ar ? "لا توجد سجلات" : "No records found"}</p>
            </div>
          ) : (
            <div className="space-y-3">
              {filtered.map(rec => {
                const info = ar ? rec.ar : rec.en;
                const isOpen = expanded === rec.id;
                return (
                  <div key={rec.id}
                    className="bg-white dark:bg-[#1a1030] rounded-2xl border border-[#e7dcee] dark:border-[#3a2560] overflow-hidden hover:shadow-md transition-all">
                    <button
                      className={`w-full flex items-center gap-4 p-5 ${ar ? "flex-row-reverse" : ""}`}
                      onClick={() => setExpanded(isOpen ? null : rec.id)}>
                      <div className={`w-11 h-11 rounded-2xl flex items-center justify-center text-xl flex-shrink-0 bg-gradient-to-br ${rec.grad}`}>
                        {rec.emoji}
                      </div>
                      <div className={`flex-1 min-w-0 ${ar ? "text-right" : ""}`}>
                        <p className="text-sm font-bold text-[#2E1A47] dark:text-[#DFC8E7] truncate">{info.title}</p>
                        <p className="text-xs text-[#2E1A47]/50 dark:text-[#DFC8E7]/50 mt-0.5">{info.doctor}</p>
                      </div>
                      <div className={`hidden sm:flex flex-col flex-shrink-0 ${ar ? "items-start" : "items-end"}`}>
                        <span className="text-[11px] font-bold px-2.5 py-1 rounded-full bg-[#f0e8f8] dark:bg-[#2E1A47]/30 text-[#46255f] dark:text-[#DFC8E7]/70">
                          {ar ? CATEGORIES.find(c => c.en === rec.category)?.ar : rec.category}
                        </span>
                        <p className="text-xs text-[#2E1A47]/35 dark:text-[#DFC8E7]/35 mt-1.5">{rec.date}</p>
                      </div>
                      <svg className={`w-4 h-4 text-[#2E1A47]/25 dark:text-[#DFC8E7]/25 flex-shrink-0 transition-transform ${isOpen ? "rotate-90" : ""} ${ar ? "rotate-180" : ""}`}
                        fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
                      </svg>
                    </button>

                    {isOpen && (
                      <div className={`border-t border-[#e7dcee] dark:border-[#2a1840] px-5 pb-5 pt-4 ${ar ? "text-right" : ""}`}>
                        <p className="text-sm text-[#2E1A47]/65 dark:text-[#DFC8E7]/65 leading-relaxed mb-4">{info.detail}</p>
                        {info.tags && info.tags.length > 0 && (
                          <div className={`flex flex-wrap gap-2 mb-4 ${ar ? "flex-row-reverse" : ""}`}>
                            {info.tags.map(tag => (
                              <span key={tag} className="text-[11px] font-semibold px-2.5 py-1 rounded-full bg-[#f0e8f8] dark:bg-[#2E1A47]/30 text-[#46255f] dark:text-[#DFC8E7]/60">
                                {tag}
                              </span>
                            ))}
                          </div>
                        )}
                        <div className={`flex gap-2 ${ar ? "flex-row-reverse" : ""}`}>
                          <button
                            onClick={() => handleDownload(rec)}
                            className={`px-4 py-2 rounded-xl text-sm font-bold border transition-all flex items-center gap-1.5 ${
                              downloaded === rec.id
                                ? "border-emerald-400 bg-emerald-50 dark:bg-emerald-900/20 text-emerald-600 dark:text-emerald-400"
                                : "border-[#e7dcee] dark:border-[#3a2560] text-[#2E1A47]/60 dark:text-[#DFC8E7]/60 hover:border-[#2E1A47]/30 hover:bg-[#f0e8f8] dark:hover:bg-[#2E1A47]/20"
                            }`}>
                            {downloaded === rec.id ? (
                              <>
                                <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round"><polyline points="20 6 9 17 4 12"/></svg>
                                {ar ? "تم التحميل" : "Downloaded!"}
                              </>
                            ) : (
                              <>
                                <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round">
                                  <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/>
                                </svg>
                                {ar ? "تحميل السجل" : "Download Record"}
                              </>
                            )}
                          </button>
                          <button className="px-4 py-2 rounded-xl text-sm font-bold border border-[#e7dcee] dark:border-[#3a2560] text-[#2E1A47]/60 dark:text-[#DFC8E7]/60 hover:border-[#2E1A47]/30 transition-all flex items-center gap-1.5">
                            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round">
                              <circle cx="18" cy="5" r="3"/><circle cx="6" cy="12" r="3"/><circle cx="18" cy="19" r="3"/>
                              <line x1="8.59" y1="13.51" x2="15.42" y2="17.49"/><line x1="15.41" y1="6.51" x2="8.59" y2="10.49"/>
                            </svg>
                            {ar ? "مشاركة" : "Share"}
                          </button>
                        </div>
                      </div>
                    )}
                  </div>
                );
              })}
            </div>
          )}
        </div>
      </section>
    </div>
  );
}
